### ISSUE TITLE
Transfer to reactjs

### ISSUE THREAD

**Issue by mjackson** [reactjs/reactjs.github.io#13]
We're merging @rackt with the @reactjs GitHub org. Just wanted to let everyone know we'll be transferring this repo over there.

We'll setup reactjs.org with this site and redirect rackt.org => reactjs.org.

**Comment by timdorr** [comment]
Will reactjs.com still point to the React site?

**Comment by mjackson** [comment]
Unsure. I was talking to @spicyj about this earlier today. My suggestion would be for reactjs.org to be the community site and reactjs.com the React site.

**Comment by mjackson** [comment]
Update: I talked to a few people at Facebook today about this. We'll hopefully have it resolved soon.

**Comment by timdorr** [comment]
I agree with the org/com split. Hopefully, TPTB agree :smile:

**Comment by kidwm** [comment]
https://github.com/react
It seems @vjeux own the @react GitHub org now?

**Comment by mjackson** [comment]
We settled on https://reactcommunity.org for now. @spicyj and others have other plans for reactjs.org.
