### ISSUE TITLE
reactcommunity.org is down

### ISSUE THREAD

**Issue by CMTegner** [reactjs/reactjs.github.io#15]
reactcommunity.org is down.

```
$ curl -I reactcommunity.org
curl: (6) Could not resolve host: reactcommunity.org
```

Looks like it was [updated yesterday](http://www.whois.com/whois/reactcommunity.org):

>Domain:reactcommunity.org
>Registrar:Tucows Inc.
>Registration Date:2016-02-16
>Expiration Date:2018-02-16
>Updated Date:2017-02-17

**Comment by ppicazo** [comment]
Whois shows the domain has been renewed, the website is accessible again.

**Comment by taion** [comment]
Closing this for now, then
