### ISSUE TITLE
Badges for project stability 

### ISSUE THREAD

**Issue by gaearon** [reactjs/reactjs.github.io#8]
Not sure where to post this so posting here. 

Do we want to establish some system to indicate how stable we consider a project to be? By this, I mean the amount of production usage a project has received and whether we plan to change APIs (react-router-redux, scroll-behavior, async-props), the project is stabilizing (history, react-router), stable (reselect, redux, react-redux), or even a little stale (react-modal)?

Does this make sense? I think this would help clarify the expectations and help people choose what they want to rely on.

**Comment by ryanflorence** [comment]
sounds great

**Comment by thejmazz** [comment]
I think calling out projects to be stale is useful - something might come up on a quick npm search and later you realize it wasn't the best. 

Definitely no negatives labeling these projects like so, however, I think some may have criticisms/issues with how the stability is determined? Metrics based or just general feel?

**Comment by taion** [comment]
It's worth clarifying where the line between "stabilizing" and "stable" is – I for one am quite surprised that React Router had a breaking API change so soon after 1.0.0; I for one didn't see that coming at all.

**Comment by gaearon** [comment]
I’d say stability is about what *we* guarantee as maintainers. For example a “stable” project can’t make breaking changes faster than once in three months, and those need to be relatively easy to apply.

**Comment by ryanflorence** [comment]
I mean, react router + history now have the (nearly crippling) contract of backwards compat, so maybe there are three badges in my head:

1. exploratory (async-props, scroll behaviors) probably shouldn't be on rackt at all
2. stable, no BC contract (redux?)
3. BC contract (router, history)
4. stale (modal) maybe should move off rackt, if nobody steps up to own it move to rackt-stale?

I made a new version of the manifesto on #7 that says that projects shouldn't really make it to Rackt until they've got some adoption/ownership. There are things here that I just tossed up before anything was popular that should probably go.

**Comment by taion** [comment]
(Rephrased my above comment to be less awkwardly worded)

Node's "stability index" is probably as good a place as any to start: https://nodejs.org/api/documentation.html#documentation_stability_index

Notably, they go straight from "experimental" to "stable".

I'd be :+1: for moving scroll-behavior off rackt, BTW – I thought it'd be a tiny thing that would require minimal support, but there's a lot more complexity there than I anticipated.

**Comment by ryanflorence** [comment]
> I thought it'd be a tiny thing that would require minimal support, but there's a lot more complexity there than I anticipated.

Yeah, which is why the manifesto says stuff doesn't come to Rackt until it's got some community usage, then it can come in to (hopefully) get great support and maintenance.

**Comment by timdorr** [comment]
> projects shouldn't really make it to Rackt until they've got some adoption/ownership. 

Maybe add a rackt-incubator for such projects? Something akin to [the Apache Incubator](http://incubator.apache.org/) or [ECMA262](https://github.com/tc39/ecma262). We can list those on rackt.org, so they gain some visibility and are known to be considered for inclusion (so others can join in the effort towards getting them up to "Rackt standards").

**Comment by mjackson** [comment]
I'm gonna delete this repo since we don't really use it.
